# Generated by Django 5.2.3 on 2025-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('resume', models.TextField()),
                ('prix', models.DecimalField(decimal_places=0, max_digits=8)),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='couvertures/')),
                ('date_publication', models.DateField()),
            ],
        ),
    ]
