# Generated by Django 5.2.3 on 2025-06-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('quantite', models.PositiveIntegerField()),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.livre')),
            ],
        ),
    ]
