# Generated by Django 5.2.3 on 2025-06-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='date_publication',
        ),
        migrations.AlterField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to='livres/'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
