# Generated by Django 5.2.3 on 2025-06-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
