# Generated by Django 5.2.3 on 2025-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0002_alter_citation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='video_fichier',
            field=models.FileField(blank=True, help_text='Ou téléversez une vidéo', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube ou autre', null=True),
        ),
    ]
