# Generated by Django 5.2.3 on 2025-06-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pasteur/')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PenseeDuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('texte', models.TextField()),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
